version: '2.20.2'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: crud_go_test
    ports:
      - "0803:0803"  
  restapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    depends_on:
      - mysql
    restart: on-failure
    environment:
      DBHOST: mysql
      DBPORT: 3306
      DBUSER: root
      DBPASS: 123
      DBNAME: crud_go_test
