name: Deploy app to API

#akan melkaukan deploy ketika push ke branch main
on:
  push:
    branches:
      - main

#jalankan docker dan install
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    #Login to docker hub
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    #build dan push dockerfile kedalam dockerhub
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUBUSERNAME }}/dataCI-CD:latest
        
  #melakukan deploy menggunakan docker
  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      #connect kedalam server menggunakan SSH
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DB_HOST }} 
          username: ${{ secrets.DBUSERNAME}} 
          key: ${{ secrets.DBKEY }} 
          port: ${{ secrets.DBPORT }} 
          script: |
            docker stop data
            docker rm data
            docker rmi ${{ secrets.DOCKERHUBUSERNAME }}/dataCI-CD:latest
            docker pull ${{ secrets.DOCKERHUBUSERNAME }}/dataCI-CD:latest
            docker run -d -p 8080:8080 -e SERVERPORT=${{ secrets.DBPORT }} -e DBUSER=${{ secrets.DBUSERNAME }} -e DBPASS=${{ secrets.DBKEY }} -e DBHOST=${{ secrets.DB_HOST }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} --name restapi ${{ secrets.DOCKERHUBUSERNAME }}/dataCI-CD:latest
         
            